notification:
    email: false
language: java

sudo: false   # Linux OS: run in container

jdk: oraclejdk9

env:
  global:
    - CODECOV_TOKEN=127975b3-f83a-48d5-8594-69981bfbab1a

addons:
  apt:
    packages:
      - oracle-java9-installer

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

install: true

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == osx ]]; then brew update; brew cask reinstall caskroom/versions/java9; fi

cache:
  directories:
  - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)
