notification:
    email: false
language: java

sudo: false   # Linux OS: run in container

jdk: oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

install: true

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == osx ]]; then brew update; brew cask reinstall caskroom/versions/java9; fi

cache:
  directories:
  - $HOME/.m2
